### PR TITLE
scorpion: move mms_useragent per device from common

### PR DESCRIPTION
**Pull request by koron393**
This url is for SGP621 (scorpion)

### CODE REVIEW

**Comment by alviteri** [comment]
can you tell me where did you found this .... because I have

uaprof  false
uaprof2 false
uaprof3 false

**Comment by koron393** [comment]
I found this decompiled stock 23.5.A.1.291 frameworks-res.apk.

**Comment by alviteri** [comment]
ok ... when I decompile frameworks-res.apk it never show config.xml

**Comment by alviteri** [comment]
@koron393 if I pass you z3 and z3c frameworks can you put the values ? because for me apktool is not giving config.xml file

**Comment by koron393** [comment]
@alviteri OK. I'll try it.

**Comment by alviteri** [comment]
@koron393 if you can't then link me the tool for it because apktool don't give config.xml here

**Comment by koron393** [comment]
@alviteri I found it at "strings.xml" in decompiled stock apk.
...Is it correct?

**Comment by alviteri** [comment]
@koron393 thanks ... please send this to m-mr1 branch too

**Pull request merged**
